#!/usr/bin/env bash
file="$2"
out="$3"
requiresfile="requires-list.txt"

#tput colors
yellow=$(tput setaf 3)
green=$(tput setaf 2)
red=$(tput setaf 1)
normal=$(tput sgr0)

missing_packages() {
  rpmbuild -ba "$file" 2>&1|grep 'is needed by' > crateparse-"$file"
  printf "%s\n" "${green}OK${normal}: Created the file ${yellow}crateparse-$file${normal}"
}

crate_parse() {
  while IFS= read -r line; do
    line=$(echo "$line"|\
        awk -F'is' '{print $1}'|\
        awk '{$1=$1;print}'| \
        sed -E 's/[()~]//g; s/^crate/rust-/g; s/ with crate/, rust-/g;s,/,+,g'
      )
    echo "$line"
  done < "$file"
}

list() {
  tf="$(mktemp)"
  crate_parse > "$tf"
  printf "%-40s %-10s %-10s %-15s %-10s\n" "Package Name" "Min Ver" "Max Ver" "Available Ver" "Installable"
  while read -r line; do
    pkg=$(echo "$line"|awk '{print $1}')
    minver=$(echo "$line"|awk '{print $3}'|sed 's/,//g')
    maxver=$(echo "$line"|awk '{print $6}'|sed 's/,//g')
    avaver=$(search_ver)
    sup=$(check_ver "$avaver" "$minver" "$maxver")
    printf "%-40s %-10s %-10s %-15s %-10s\n" "$pkg$out" "$minver" "$maxver" "$avaver" "$sup"
  done < "$tf"
  rm -f "$tf"
}

create_build_requires(){
  brf="$(mktemp)"
  crate_parse > "$brf"
  while read -r line; do
    echo "$line"
  done < "$brf"
}

check_ver(){
  local sup
  if [[ ("$avaver" > "$minver" || "$avaver" == "$minver" ) && "$avaver" < "$maxver" ]];then
    sup="${green}OK${normal}"
  elif [[ ( -z "$minver" || -z "$maxver" ) && ( -n "$avaver" ) ]];then
    sup="${green}OK${normal}"
  else
    sup="${red}NOT${normal}"
  fi
  printf "%s" "$sup"
}

search_ver(){
  local getver
  for i in $pkg$out;do
    getver=$(dnf info "$i" 2>&1 /dev/null |\
      grep 'Version'|\
      awk -F':' '{print $2}'|\
      awk '{$1=$1;print}')
    if [ -z "$getver" ]; then
      getver="Missing Package"
      break
		fi
  done
  printf "%s" "$getver"
}

install_dep() {
  for i in $(crate_parse);do
		echo "Searching $i"
    sudo dnf -y install "$i""$out"
  done

}

cmd() {
  case "$1" in
    generate)
      missing_packages
  	;;
  	search)
  		search_dep
  	;;
  	install)
  		install_dep
  	;;
    list)
      list
    ;;
    requires)
      crate_parse
      #create_build_requires
    ;;
  	*)
  		echo -e "Usage:
  		$0 generate specfile # generate the dependencies parses
  		$0 search parsedep # use the generated parse file to search for dependencies
  		$0 install parsedep # use to install the parsed dependencies
  		"
  esac
}

main() {
  cmd "$@"
}

main "$@"
