#!/usr/bin/env bash
# download crates files using name and version
name="$1"
version="$2"
crate_api="https://crates.io/api/v1/crates"
if [ "$#" -eq 0 ];then
  echo -e "\033[0;31mERROR: No Name and Version was informed\033[0m"
  exit 1
fi
curl -L "$crate_api"/"$name"/"$version"/download -o "$name"-"$version".crate
