#!/usr/bin/env bash
name=$(basename "$0")
cmd="$1"
file="$2"
out="$3"
install="$4"
version="$5"
crate_api="https://crates.io/api/v1/crates"
build_root="${BUILD_ROOT:-$HOME/rpmbuild/SOURCES/}"

#tput colors
yellow=$(tput setaf 148)
green=$(tput setaf 40)
red=$(tput setaf 9)
cyan=$(tput setaf 87)
normal=$(tput sgr0)

missing_packages() {
  rpmbuild -ba "$file" 2>&1|grep 'is needed by' > "${name}-$file"
  printf "%s\n" "${green}OK${normal}: Created the file ${yellow}${name}-$file${normal}"
}

get_crate() {
  name="$2"
  version="$3"
  curl -L "$crate_api"/"$name"/"$version"/download -o "$build_root$name-$version.crate"
}

crate_parse() {
  while IFS= read -r line; do
    line=$(echo "$line"|\
      awk -F'is needed by' '{print $1}'|\
      awk '{$1=$1;print}'|\
      sed -E 's/[()~]//g;
          s/^crate/rust-/g;
          s/ with crate/, rust-/g;
					s,/,+,g'|\
			sed -e "s/\(rust[-[:alnum:]*]\{2,\}\)/\1$version/g;
							s/\(rust-\S*\)/\1$out/g"
      )
    echo "$line"
  done < "$file"
}

search_dep() {
  tf="$(mktemp)"
  crate_parse > "$tf"
  printf "%-40s %-10s %-10s %-15s %-10s\n" "Package Name" "Min Ver" "Max Ver" "Available Ver" "Status"
  while read -r line; do
    pkg=$(echo "$line"|awk '{print $1}')
    minver=$(echo "$line"|awk '{print $3}'|sed 's/,//g')
    maxver=$(echo "$line"|awk '{print $6}'|sed 's/,//g')
    avaver=$(search_ver)
    sup=$(check_ver "$avaver" "$minver" "$maxver" "$pkg")
    printf "%-40s %-10s %-10s %-15s %-10s\n" "$pkg" "$minver" "$maxver" "$avaver" "$sup"
  done < "$tf"
  rm -f "$tf"
}

create_build_requires(){
  brf="$(mktemp)"
  crate_parse > "$brf"
  sed -i 's/^/BuildRequires:  /' "$brf"
  cat "$brf"
  rm -f "$brf"
}

check_ver(){
  local sup
  if [[ ("$avaver" > "$minver" || "$avaver" == "$minver" ) && "$avaver" < "$maxver" ]];then
    sup="${green}FOUND${normal}"
    install_dep "$pkg" "$install" "$version"
  elif [[ ( -z "$minver" || -z "$maxver" ) && ( -n "$avaver" ) ]];then
    sup="${green}FOUND${normal}"
    install_dep "$pkg" "$install" "$version"
  else
    sup="${red}LOSS${normal}"
  fi
  printf "%s" "$sup"
}

search_ver(){
  local getver
  for i in $pkg;do
    getver=$(dnf info "$i" 2>&1 /dev/null |\
      grep 'Version'|\
      awk -F':' '{print $2}'|\
      awk '{$1=$1;print}')
    if [ -z "$getver" ]; then
      getver="Missing Version"
      break
    fi
  done
  printf "%s" "$getver"
}

install_dep() {
  install="$4"
  if [[ ( -n "$install" && "$install" == "-i" ) ]];then
    sudo dnf -y install "$pkg" > /dev/null 2>&1
  fi
}

show_missing_declared(){
  rpmbuild -ba "$file" 2>&1|grep "$out"|awk '{$1=$1;print}'|awk '{print $1}'|uniq
}

show_help(){
  printf "Usage:\n"
  declare -A cmd_help=(
    [init]="# generates a specter file for parsing missing dependencies"
    [search]="# search, list or install dependencies"
    [requires]="# print a BuildRequires list"
    [declared]="# list the declared missing dependencies from the spec file"
    [parse]="# print the parsing result from the specter file"
    [getcrate]="# Download a crate file, using name and version"
    [help]="# this help command"
  )
  for key in "${!cmd_help[@]}";do
    value="${cmd_help[$key]}"
    printf "%-13s %s\n" "${green}$key" "${normal}$value"
  done

  echo -ne "Examples:
  # Creating the $name-foo.spec file for parsing dependencies
  ${cyan}${name} ${green}init ${yellow}foo.spec${normal}

  # Using the $name-foo.spec file to search missing packages
  ${cyan}${name} ${green}search ${yellow}$name-foo.spec${normal}

  # search version 3 and appending the word \"-devel\"
  ${cyan}${name} ${green}search ${yellow}${name}-foo.spec ${red}-devel 3${normal}

  # you can automatically install the missing packages when searching
  ${cyan}${name} ${green}search ${yellow}$name-foo.spec ${red}-devel -i${normal}

  # copying the BuildRequires list to the clipboard, to be used on the foo.spec file
  ${cyan}${name} ${green}requires ${yellow}$name-foo.spec${red}|xsel --clipboard${normal}

  # downloading bar-0.1.0.crates to $HOME/rpmbuild/SOURCES/
  ${cyan}${name} ${green}getcrate ${yellow}bar ${red}0.1.0${normal}

  # downloading bar-0.1.0.crate to a custom path
  ${red}BUILD_ROOT=/opt/rpmbuild/SOURCES/ ${cyan}${name} ${green}getcrate ${yellow}bar ${red}0.1.0${normal}

  #listing the still missing packages declared as BuildRequires in foo.spec
  ${cyan}${name} ${green}declared ${yellow}foo.spec${normal}

  # print the $name-foo.spec parsing style
  ${cyan}$name ${green}parse ${yellow}$name-foo.spec ${red}-devel${normal}
"
}

main() {
  case "$cmd" in
    init)
      missing_packages
    ;;
    search)
      search_dep
    ;;
    requires)
      create_build_requires
    ;;
    declared)
      show_missing_declared
    ;;
    parse)
      crate_parse
    ;;
    getcrate)
      get_crate "$@"
    ;;
    help)
      show_help
    ;;
    *)
      show_help
    ;;
  esac
}

main "$@"
